server:
  port: 6000
  
spring:
  application:
    name: authentication-server

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/authentication_db
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
  cloud:
    discovery:
      enabled: false
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    
jwt:
  secret: stock-market-app
  expiryTimeMs: 36000000
